CREATE TABLE `report_data_template_banner` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `report_id` bigint(20) NOT NULL,
  `group_id` bigint(20) DEFAULT NULL,
  `period` varchar(50) DEFAULT NULL,
  `num` varchar(100) DEFAULT NULL,
  `part_name` varchar(20) DEFAULT NULL,
  `level` int(11) DEFAULT NULL,
  `dim_date` datetime DEFAULT NULL,
  `dim_com` varchar(100) DEFAULT NULL,
  `dim1` varchar(100) DEFAULT NULL,
  `dim2` varchar(100) DEFAULT NULL,
  `dim3` varchar(100) DEFAULT NULL,
  `dim4` varchar(100) DEFAULT NULL,
  `dim5` varchar(100) DEFAULT NULL,
  `mea_int1` bigint(20) DEFAULT NULL,
  `mea_int2` bigint(20) DEFAULT NULL,
  `mea_int3` bigint(20) DEFAULT NULL,
  `mea_int4` bigint(20) DEFAULT NULL,
  `mea_int5` bigint(20) DEFAULT NULL,
  `mea_float1` double DEFAULT NULL,
  `mea_float2` double DEFAULT NULL,
  `mea_float3` double DEFAULT NULL,
  `mea_float4` double DEFAULT NULL,
  `mea_float5` double DEFAULT NULL,
  `mea_float6` double DEFAULT NULL,
  `mea_float7` double DEFAULT NULL,
  `mea_float8` double DEFAULT NULL,
  `mea_float9` double DEFAULT NULL,
  `mea_float10` double DEFAULT NULL,
  `load_time` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `app_ids` (`report_id`,`group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
